### ISSUE TITLE
Immich v1.118.0

### ISSUE THREAD

**Issue by derpderpington** [romainrbr/immich-face-to-album#14]
New api update specifically "/api/people/:id/assets" have been removed. Wondering if it is safe to update to Immich v1.118.0

**Comment by jbrechtel** [comment]
Immich 1.118.0 will indeed break the script but upon inspection it appears that while this script is making an API call to /api/people/:id/assets that the results aren't being used?

Not sure what's going on there. Maybe it was accidentally left in or something?

**Comment by romainrbr** [comment]
Thanks @jbrechtel for the heads up, I've removed the dead code, as well as added a `--verbose` flag in the latest release !

@derpderpington : The latest release should be compatible with v1.118.0 (at least its working fine on my end), thanks for the question !

**Comment by derpderpington** [comment]
@romainrbr just updated and all is working! Thanks!
