### ISSUE TITLE
Unable to run on schedule

### ISSUE THREAD

**Issue by figlizzard12** [romainrbr/immich-face-to-album#2]
Using Unraid docker container to host Immich and set up a custom user script to try get this working. 

Every single time I close a console connection to the container, 'immich-face-to-album' isn't recognized and I need to run the installation again. Which is silly. 

This might be why the script fails every time. But the '@hourly' or '@daily' prompts aren't working either, or using CRON.

**Comment by romainrbr** [comment]
Hello @figlizzard12 , this is most likely because you are using the command inside the docker container (which gets recreated with every immich update).

You could run it from outside the docker container (easier), or create a custom Docker image that includes it.
